name: Check documentation
on: push
jobs:
  check:
    if: github.repository == 'msluszniak/react-native-executorch'
    runs-on: ubuntu-latest
    concurrency:
      group: docs-check-${{ github.ref }}
      cancel-in-progress: true
    env:
      WORKING_DIRECTORY: docs
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Cache
        working-directory: ${{ /home/runner/work/react-native-executorch/react-native-executorch }}
        # the mkdir is a workaround to avoid this: https://github.com/actions/setup-node/issues/317
        run: mkdir -p .yarn/cache
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Run Yarn
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
      - name: Generate docs
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build
